spring:
  application:
    name: elastic-query-web-client
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: elastic_query_web
  cloud:
    config:
      name: elastic-query-web-client,config-client