spring:
  application:
    name: elastic-query-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: elastic_query
  cloud:
    config:
      name: elastic-query-service,config-client