spring:
  application:
    name: reactive-elastic-query-web-client
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: reactive_elastic_query_web
  cloud:
    config:
      name: reactive-elastic-query-web-client,config-client