spring:
  application:
    name: twitter-to-kafka-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: twitter_to_kafka
  cloud:
    config:
      name: twitter-to-kafka-service,config-client