spring:
  application:
    name: kafka-to-elastic-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: kafka_to_elastic
  cloud:
    config:
      name: kafka-to-elastic-service,config-client