spring:
  application:
    name: elastic-query-web-client-multiply
  profiles:
    active: elastic_query_web_multiply
  cloud:
    config:
      name: elastic-query-web-client-multiply,config-client
      uri: http://localhost:8888
      username: spring_cloud_user
      password: '1234'

logging:
  level:
    root: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: elastic-query-web-client-multiply